# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Evan's Blog
tagline:          'Now This is a Tagline!'
description:      'Overanalyzing Simple Questions since 2016.'
url:              http://ecurtin2.github.io
baseurl:          /

author: 'Evan Curtin'

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]
mailto: mailto:evanmcurtin@gmail.com
github: ecurtin2
linkedin: https://www.linkedin.com/in/evanmcurtin
repo: https://github.com/ecurtin2/ecurtin2.github.io

google_analytics: UA-81645801-1
disqus: ecurtin2-blog
